### ISSUE TITLE
NullReferenceException in TextBuffer_PostChanged -> Wrapper.Wrap

### ISSUE THREAD

**Issue by ite-klass** [emartineau/SelectionWrapper#8]
I am not sure what I did specifically but a `NullReferenceException` occurred.
```
3080 | ERROR | System.NullReferenceException: Object reference not set to an instance of an object.
   at SelectionWrapper.Wrapper.Wrap(ITextBuffer textBuffer)
   at SelectionWrapper.EditorListener.TextBuffer_PostChanged(Object sender, EventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)
 --- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

3081 | ERROR | System.NullReferenceException: Object reference not set to an instance of an object.
   at SelectionWrapper.Wrapper.Wrap(ITextBuffer textBuffer)
   at SelectionWrapper.EditorListener.TextBuffer_PostChanged(Object sender, EventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)
 --- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by emartineau** [comment]
Hmm... I think this might relate to (#3). I made some changes that ended up removing the null check I put in place there. Just added some null checks for the selection implementation the extension now uses. Let me know if it comes up again. Thanks!
